# Generated by Django 3.1.7 on 2021-03-13 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritelist',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
    ]
