# Generated by Django 3.1.7 on 2021-03-11 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20210311_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritelist',
            old_name='companies',
            new_name='company',
        ),
    ]
