# Generated by Django 3.1.7 on 2021-03-13 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20210313_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritelist',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
    ]
